# Permalinks
permalink:        pretty

# Highlighter
highlighter: rouge

# Setup
title:            LankyLord.NET
tagline:          'A small site about me'
description:      'IT Technician. Anime, LN, and manga fan. Brother of the PC Master Race.'
url:              http://lankylord.net

author:
  name:           'Scott Kendall'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
